// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0gTVDi0qyQ2niOeHfEEU_WxmVPycybUA',
    appId: '1:726128096469:web:40e2fce3827985074b9e5c',
    messagingSenderId: '726128096469',
    projectId: 'smart-city-emergency-dba58',
    authDomain: 'smart-city-emergency-dba58.firebaseapp.com',
    storageBucket: 'smart-city-emergency-dba58.firebasestorage.app',
    measurementId: 'G-FSZER8PXL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxIb5vOhB_ZXnoxaoMj1L5rHZNj0-hNl0',
    appId: '1:726128096469:android:be53f3a47172af714b9e5c',
    messagingSenderId: '726128096469',
    projectId: 'smart-city-emergency-dba58',
    storageBucket: 'smart-city-emergency-dba58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDfLtqaDDtNuNmtQfHQeU94B4Agrjgods',
    appId: '1:726128096469:ios:7391cc369c4245864b9e5c',
    messagingSenderId: '726128096469',
    projectId: 'smart-city-emergency-dba58',
    storageBucket: 'smart-city-emergency-dba58.firebasestorage.app',
    iosClientId: '726128096469-tlob20uc3r0iol70lqfae827mtr7egll.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCityEmergencySystem',
  );
}
