import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:provider/provider.dart';

import 'services/firebase_service.dart';
import 'services/auth_service.dart';
import 'services/location_service.dart';
import 'services/api_service.dart';
import 'services/notification_service.dart';
import 'services/routing_service.dart';
import 'utils/theme.dart';

import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/home_screen.dart';
import 'screens/map_screen.dart';
import 'screens/emergency_screen.dart';
import 'screens/profile_screen.dart';
import 'firebase_options.dart';

/// Global navigator key so notification taps can navigate.
final GlobalKey<NavigatorState> appNavigatorKey = GlobalKey<NavigatorState>();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    // Uses values generated by `flutterfire configure` (see README).
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    
    await FirebaseAppCheck.instance.activate(
      androidProvider: AndroidProvider.playIntegrity,
      appleProvider: AppleProvider.deviceCheck,
      webProvider: ReCaptchaV3Provider('recaptcha-v3-site-key'),
    );

    FirebaseFirestore.instance.settings = const Settings(
      persistenceEnabled: true,
      cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
    );
  } catch (e) {
    debugPrint('Firebase initialization failed: $e');
  }

  final firebaseService = FirebaseService();

  // Initialize notifications after Firebase is ready.
  final notificationService = NotificationService(firebaseService: firebaseService);
  await notificationService.init(navigatorKey: appNavigatorKey);

  runApp(
    MultiProvider(
      providers: [
        Provider<FirebaseService>.value(value: firebaseService),
        Provider<AuthService>(create: (_) => AuthService(firebaseService: firebaseService)),
        Provider<LocationService>(create: (_) => LocationService()),
        Provider<ApiService>(create: (_) => ApiService(firebaseService: firebaseService)),
        Provider<RoutingService>(create: (_) => RoutingService()),
        Provider<NotificationService>.value(value: notificationService),
      ],
      child: const SmartCityApp(),
    ),
  );
}

class SmartCityApp extends StatelessWidget {
  const SmartCityApp({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = context.read<AuthService>();

    return MaterialApp(
      navigatorKey: appNavigatorKey,
      title: 'SmartCityEmergencySystem',
      theme: AppTheme.lightTheme,
      themeMode: ThemeMode.light,
      debugShowCheckedModeBanner: false,
      home: StreamBuilder(
        stream: authService.authStateChanges(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(body: Center(child: CircularProgressIndicator()));
          }

          if (snapshot.hasData && snapshot.data != null) {
            return const HomeScreen();
          }

          return const LoginScreen();
        },
      ),
      routes: {
        LoginScreen.routeName: (_) => const LoginScreen(),
        SignupScreen.routeName: (_) => const SignupScreen(),
        '/map': (_) => const MapScreen(),
        '/emergency': (_) => const EmergencyScreen(),
        '/profile': (_) => const ProfileScreen(),
      },
    );
  }
}

